# Generated by Django 2.2.3 on 2021-02-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myinfo',
        ),
    ]
