# Generated by Django 2.2.3 on 2021-02-21 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0003_place_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=datetime.datetime(2021, 2, 21, 4, 17, 8, 951333, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
