# Generated by Django 2.2.3 on 2021-02-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0004_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
